name: ExpenseAgent
options:
  bundleIdPrefix: ai.e6
  deploymentTarget:
    iOS: "17.0"
targets:
  ExpenseAgent:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.e6.expense-agent
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_VERSION: "5.9"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_NSCameraUsageDescription: "ExpenseAgent needs camera access to scan receipts"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "ExpenseAgent needs photo library access to import receipt images"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
